spring:
  application:
    name: sync
  profiles:
    active: dev
  flyway:
    enabled: false
server:
  port: 8081
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 12345678
logging:
  level:
    io.xxx.sync.core.AbstractSynchronizer: debug